In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Q1

### Generate two lists of student scores for math and physics.
### Convert to Pandas DataFrame.
### Calculate the covariance using .cov.
### Calculate Pearson correlation coefficient using corr(method='pearson').
### Shuffle one of the score lists randomly.
### Now calculate Spearman rank correlation using corr(method='spearman).
### Discuss the difference between Pearson and Spearman.

In [28]:
maths_score = np.random.randint(40,100,size=50)

In [29]:
physics_score = np.random.randint(40,100,size=50)

In [30]:
df = pd.DataFrame({
    "Maths" : maths_score,
    "Physics" : physics_score 
})
df.head()

   Maths  Physics
0     96       77
1     54       42
2     96       74
3     50       61
4     89       50

Doing Correlation And  Using Built in Function.

### Covariance

In [31]:
covariance = df.cov()
print(f"Covariance:\n{covariance}\n")

Covariance:
              Maths     Physics
Maths    349.030612   49.263265
Physics   49.263265  307.815918

### Pearson Correlation

In [32]:
pearson_correlation = df.corr(method="pearson")
print(f"Pearson Correlation:\n{pearson_correlation}\n")

Pearson Correlation:
            Maths   Physics
Maths    1.000000  0.150295
Physics  0.150295  1.000000

In [33]:
shuffled_physics_score = np.random.shuffle(physics_score)
spearmen_correlation = df.corr(method="spearman")
spearmen_correlation

           Maths  Physics
Maths    1.00000  0.14843
Physics  0.14843  1.00000

| Feature                | Pearson              | Spearman                    |
| ---------------------- | -------------------- | --------------------------- |
| Measures               | Linear relationship  | Monotonic relationship      |
| Based on               | Actual values        | Ranked values               |
| Sensitive to shuffling | Highly               | Highly                      |
| Original data          | 0.21 (weak positive) | \~0.25 (if monotonic trend) |
| After shuffling        | Near 0               | Near 0                      |

# Q2

### Generate and plot a uniform distribution using NumPy.
### Use a histogram with 50 bins.
### Generate a binomial distribution using NumPy or scipy.stats.binom.
### Compare it visually with a normal distribution.
### Simulate a Poisson distribution of daily customer counts.
### Plot and interpret.